### ISSUE TITLE
Changes to about.md does not update the website (wrong page read when deploying template)

### ISSUE THREAD

**Issue by ranakroychowdhury** [academicpages/academicpages.github.io#2072]
**Describe the bug**
On some days, if I make some changes _pages/about.md and commit, it updates the website. On other days, if I make similar changes to the same file, it won't update.

However, if I upload a new pdf file, like my CV, then the new CV does show up on the website. 

My repository is public.

I cleared my browser cache.

Unpublish and republish the website

Re-run all jobs.

But nothing worked.

**To Reproduce**
1. Go to https://github.com/ranakroychowdhury/ranakroychowdhury.github.io/blob/master/_pages/about.md
2. Make any change to it.
4. Find that the website at https://ranakroychowdhury.github.io/ doesn't incorporate the changes.

**Expected behavior**
I expected the changes to about.md file to update on the website.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.4.1
 - Browser: Firefox but the issue persists across Chrome too

**Comment by rjzupkoii** [comment]
How much time are you giving between when you commit and push the changes to when you check the live website? While GitHub can be quick sometimes, others times it can take up to 10 to 15 minutes before the changes are deployed. If you go into the [commit logs](https://github.com/ranakroychowdhury/ranakroychowdhury.github.io/commits/master/) you will notice the green checks next to the commits - this shows up once GitHub is done running the deployment scripts.

**Comment by ranakroychowdhury** [comment]
It has been several days since I made the change. I do notice the green checks next to the commits but the changes are not visible on the website.

**Comment by rjzupkoii** [comment]
@ranakroychowdhury Can you make an edit, commit, push to GitHub, and then link to the change from the commit log?

**Comment by ranakroychowdhury** [comment]
Thanks for the prompt response @rjzupkoii .

Here is the [commit log](https://github.com/ranakroychowdhury/ranakroychowdhury.github.io/commit/a5a4191e39118414cfeb0df9637fd76cd5928241) to a change I just made now.

It adds the line "Sample change that doesn't update website, as requested by @rjzupkoii." at the top of about.md file and should appear at the very top of the [website](https://ranakroychowdhury.github.io/).

**Comment by rjzupkoii** [comment]
@ranakroychowdhury It looks like everything was deployed correctly; however, I did find [this ticket over on the GitHub Community](https://github.com/orgs/community/discussions/19713) that suggests that this might be an issue with the CDN refreshing. If that's the case then it might just take awhile before the page updates.

**Comment by ranakroychowdhury** [comment]
Thanks for the update @rjzupkoii . I went through the whole ticket but none of the proposed solutions worked. I understand it may take awhile for updates but it's never updating at all, not even in weeks.

**Comment by rjzupkoii** [comment]
@ranakroychowdhury I just pushed a small change to the template and the page refreshed once it was it was deployed. Nothing is really standing out to me as the cause of your problem other than that it might be something on GitHub's side since the [deploy process is reporting success](https://github.com/ranakroychowdhury/ranakroychowdhury.github.io/actions/runs/8839193458/job/24272017696).

**Comment by ranakroychowdhury** [comment]
I saw your change and it reflects on your webpage. I'm still not sure what the issue on my side is. Thank you so much for being so responsive and helpful. Really appreciate it.

**Comment by rjzupkoii** [comment]
@ranakroychowdhury Have there been any updates on this? Were you able to open a ticket with GitHub directly?

**Comment by ranakroychowdhury** [comment]
Hi,
Thanks for following up. The issue still persists where my github page is still showing a version of the website that I pushed 2 years ago and doesn't show any of the changes I made over the last few weeks. I created a ticket at https://support.github.com/ticket/personal/0/2774475. I'll inform you as soon as I get to know something.

**Comment by ranakroychowdhury** [comment]
Hi @rjzupkoii,
The Github team replied to the issue. It seems that the file being used to populate my website with the body text appears to be `/private_images/about.md `rather than `/_pages/about.md`. Once I deleted the `private_images` folder, the website was correctly populated from `/_pages/about.md`. Thanks for helping me through this. Appreciate it.

**Comment by rjzupkoii** [comment]
@ranakroychowdhury Glad to hear it's working and that is really interesting that it was trying to deploy using the `private_images` folder instead of `/_pages/about.md` -  did they mention anything about why it was reading from that directory? I'm just trying to determine if there's a bug in the template I need to address, or something that I should add to the Wiki for future reference.

**Comment by ranakroychowdhury** [comment]
Hi @rjzupkoii , I'm copying their exact reply:

`Hi Ranak,
 
Thank you for getting in touch with GitHub Support!
 
I have done some testing with a copy of your repository, and the file that is being used to populate your website with the body text appears to be /private_images/about.md rather than /_pages/about.md. If you make changes to /private_images/about.md instead - or copy the entire contents of /_pages/about.md into it, you should see those updates reflected on your website.
 
I hope this helps, please let me know if you have anything else I can assist with.
 
Roy
GitHub Support`

They don't mention anything about why it was reading from one about.md instead of the other. Personally from my experience, I did find that sometimes it would read from the /_pages/ folder while at other times it would read from the /private_images/ folder. Not sure why that was the case.

**Comment by rjzupkoii** [comment]
Interesting, that at least points in the direction of something to being on the lookout for in the template's code though!

**Comment by rjzupkoii** [comment]
Flagging this ticket as a bit since it suggests that the template will use the wrong file when deploying if more than one option is present (i.e., in `prviate_images` instead of `_pages`. This needs to be verified with testing and an examination of the Jekyll documentation. If it is indeed the case then, it will remain to be see what type of fix is needed.

**Comment by rjzupkoii** [comment]
Haven't really been able to reproduce this error either. Closing for the time being.
