### ISSUE TITLE
Inadequate width for table of content in right sidebar + fixed colors under light/dark theme

### ISSUE THREAD

**Issue by nathanpainchaud** [academicpages/academicpages.github.io#3019]
**Describe the bug**
Same issue as in #221. However, none of the solutions/workarounds suggested in that issue seem to work here.

When including a Table of Content in a page on my website, the default width of the right sidebar is not sufficient to display the content properly. The result, as it appears on [my website](https://nathanpainchaud.github.io/cv/). can be seen in the screenshot below.

![Image](https://github.com/user-attachments/assets/06b9bcf7-c478-4dae-a0de-df7831146840)

The same website is displayed fine on mobile, see below.

![Image](https://github.com/user-attachments/assets/eb234842-a420-4702-80b7-4f42191df287)

P.S. I don't know if this is expected, but the ToC's theme doesn't change when switching between light/dark theme for the website. See screenshot below when using dark theme:

![Image](https://github.com/user-attachments/assets/afbb3f7f-6a5b-43fc-a174-65a1b422f38c)

**To Reproduce**
Follow the link to my website: [https://nathanpainchaud.github.io/cv/](https://nathanpainchaud.github.io/cv/).

Or include a ToC to a page in the base template. I'm not knowledgeable about Jekyll / web dev in general, so I've only changed the template's content. I have not changed any CSS files that would affect the theme.

**Expected behavior**
The ToC should adapt to the width of its content, or if not easily possible then have a larger default width.

**Screenshots**
See above in the description of the bug.

**Browser (please complete the following information):**
 - Device:
 ```console
↪ inxi -G
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Barcelo driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 21.1.16 with: Xwayland v: 24.1.6 driver: X:
    loaded: amdgpu unloaded: modesetting dri: radeonsi gpu: amdgpu
    resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 25.0.4-arch1.1
    renderer: AMD Radeon Graphics (radeonsi renoir ACO DRM 3.61 6.14.4-arch1-2)
  Info: Tools: api: eglinfo,glxinfo x11: xdpyinfo, xprop, xrandr
```
 - OS: Linux EndeavourOS (arch-based), kernel version 6.14.4-arch1-2
 - Browser: Tested on 3 browsers, all with the same behavior.
   - Chrome: Version 136.0.7103.59 (Official Build) (64-bit)
   - Firefox: 138.0.1 (64-bit)
   - Vivaldi: 7.3.3635.11 (Stable channel) stable (64-bit)
 - Version: Up-to-date with commit ef8e08b653e57d26e6f0e3086edcd12df077c431 on main branch.

**Additional context**
Characteristics of the mobile device that properly renders the ToC:
- Device: Pixel 7A
- OS: latest Android 15 update
- Browser: Vivaldi for Android, version 7.2.3628.126

**Comment by rjzupkoii** [comment]
It looks like the only place that `toc` is exposed in the template is on the [Terms ](https://academicpages.github.io/terms/) page which doesn't appear to be linked from anywhere else. So easy to overlook during testing. The styling appears to be controlled by `_sass/layout/_navigation.scss` starting around line 379 but more investigation will be needed.

**Comment by rjzupkoii** [comment]
Looks like these settings in [_sass/_themes.scss]

```scss
$right-sidebar-width-narrow : 20px !default;
$right-sidebar-width        : 30px !default;
$right-sidebar-width-wide   : 40px !default;
```

Setting `$right-sidebar-width` to `auto` might resolve the size issue as a temporary fix.

**Comment by nathanpainchaud** [comment]
> Setting `$right-sidebar-width` to `auto` might resolve the size issue as a temporary fix.

That's the thing that I find puzzling. In #221, users also suggested to set these values as a workaround. However, nothing I've tried (e.g. setting to `auto` like you've suggested, or `float` or `200px` like in #221) impacts the appearance of the ToC in the sidebar. When I inspect the sidebar in the developper tools, its width is always 30px (when in fullscreen mode).

Could the value of `right-sidebar-width` be overridden somewhere else, or ignored entirely?

I would also note that the ToC is displayed correctly on desktop when it appears above the page (e.g. when the browser's window uses half the width of the screen), see screenshot below.

![Image](https://github.com/user-attachments/assets/babd1e66-d2cb-4f8e-89bb-7c1c0f56d235)

**Comment by rjzupkoii** [comment]
@nathanpainchaud Setting `.sidebar__right` to `auto` in the developer tools seems to set the TOC to the correct width, but it's going to take a bit of time to dig through everything to see if there's a default for `aside` somewhere that's hard coded. There's been a fair bit of code drift since #221 was created which is why a lot of the older tickets really aren't that useful for information.

**Comment by rjzupkoii** [comment]
The latest push should fix the default with of the sidebar. It looks like the theme is being rendered in dark mode correctly since the sidebar is made up of links - so a fair amount of additional customization would / will be needed for the sidebar to look dramatically different in dark mode.

**Comment by nathanpainchaud** [comment]
> The latest push should fix the default with of the sidebar.

I could have sworn I tried to change the values to `auto` locally, but that it didn't fix the ToC when I tried it... I confirm that your push fixed the display on my website! Thanks for being so reactive on this 🙂 

> It looks like the theme is being rendered in dark mode correctly since the sidebar is made up of links - so a fair amount of additional customization would / will be needed for the sidebar to look dramatically different in dark mode.

Okay! I was just wondering if the dark theme ToC was expected to be lighter than the rest of the page. If it takes a lot of customization to make darker, than I agree it's not necessarily worth it (certainly not a priority), since with the ToC width fix it's perfectly readable now in either light/dark mode!

**Comment by rjzupkoii** [comment]
@nathanpainchaud Yes, I would say for now that the dark theme ToC is working as expected. It looks like all of the code is in place for it's style to be customized more, but my graphic design skills are fairly unimpressive so coming up with a good theme for the ToC in dark mode would take me awhile. That being said, I did try to make the support for additional themes fairly straightforward so hopefully we will get some more added by contributors.
